export default {
  tasks: [
    {
      id: "1",
      name: 'Nombre de la tarea',
      date_start: '2020-01-01',
      date_end: '2020-01-10',
      level: 8,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game'],
      status: 'en cola',
    },
    {
      id: "2",
      name: 'Nombre de la tarea 01',
      date_start: '2020-11-01',
      date_end: '2020-01-10',
      level: 10,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game', 'comida', 'deporte', 'saludable'],
      status: 'en proceso',
    },
    {
      id: "3",
      name: 'Nombre de la tarea 02',
      date_start: '2020-01-01',
      date_end: '2020-01-10',
      level: 4,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game'],
      status: 'terminada',
    },
    {
      id: "4",
      name: 'Nombre de la tarea 03',
      date_start: '2020-01-01',
      date_end: '2020-01-10',
      level: 6,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game', 'tareas'],
      status: 'en cola',
    },
    {
      id: "5",
      name: 'Nombre de la tarea 04',
      date_start: '2020-01-01',
      date_end: '2020-01-10',
      level: 10,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game'],
      status: 'en proceso',
    },
    {
      id: "6",
      name: 'Nombre de la tarea 05',
      date_start: '2020-01-01',
      date_end: '2020-01-10',
      level: 6,
      person_create: 'Alejandro Herrera',
      person_assigned: 'Maximiliano Opitz',
      tags: ['car', 'play', 'game'],
      status: 'terminada',
    },
  ],
};
